//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resumableUpload.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ebys.aa.com.tr/", ConfigurationName="ServiceReference1.signdocumentSoap")]
    public interface signdocumentSoap {
        
        // CODEGEN: Generating message contract since element name ServisKullaniciAdi from namespace https://ebys.aa.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ebys.aa.com.tr/Sign", ReplyAction="*")]
        resumableUpload.ServiceReference1.SignResponse Sign(resumableUpload.ServiceReference1.SignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ebys.aa.com.tr/Sign", ReplyAction="*")]
        System.Threading.Tasks.Task<resumableUpload.ServiceReference1.SignResponse> SignAsync(resumableUpload.ServiceReference1.SignRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sign", Namespace="https://ebys.aa.com.tr/", Order=0)]
        public resumableUpload.ServiceReference1.SignRequestBody Body;
        
        public SignRequest() {
        }
        
        public SignRequest(resumableUpload.ServiceReference1.SignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ebys.aa.com.tr/")]
    public partial class SignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ServisKullaniciAdi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ServisParola;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Konu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PersonelSicil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DokumanHash;
        
        public SignRequestBody() {
        }
        
        public SignRequestBody(string ServisKullaniciAdi, string ServisParola, string Konu, string PersonelSicil, string DokumanHash) {
            this.ServisKullaniciAdi = ServisKullaniciAdi;
            this.ServisParola = ServisParola;
            this.Konu = Konu;
            this.PersonelSicil = PersonelSicil;
            this.DokumanHash = DokumanHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignResponse", Namespace="https://ebys.aa.com.tr/", Order=0)]
        public resumableUpload.ServiceReference1.SignResponseBody Body;
        
        public SignResponse() {
        }
        
        public SignResponse(resumableUpload.ServiceReference1.SignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ebys.aa.com.tr/")]
    public partial class SignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SignResult;
        
        public SignResponseBody() {
        }
        
        public SignResponseBody(System.Xml.Linq.XElement SignResult) {
            this.SignResult = SignResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface signdocumentSoapChannel : resumableUpload.ServiceReference1.signdocumentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class signdocumentSoapClient : System.ServiceModel.ClientBase<resumableUpload.ServiceReference1.signdocumentSoap>, resumableUpload.ServiceReference1.signdocumentSoap {
        
        public signdocumentSoapClient() {
        }
        
        public signdocumentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public signdocumentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public signdocumentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public signdocumentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        resumableUpload.ServiceReference1.SignResponse resumableUpload.ServiceReference1.signdocumentSoap.Sign(resumableUpload.ServiceReference1.SignRequest request) {
            return base.Channel.Sign(request);
        }
        
        public System.Xml.Linq.XElement Sign(string ServisKullaniciAdi, string ServisParola, string Konu, string PersonelSicil, string DokumanHash) {
            resumableUpload.ServiceReference1.SignRequest inValue = new resumableUpload.ServiceReference1.SignRequest();
            inValue.Body = new resumableUpload.ServiceReference1.SignRequestBody();
            inValue.Body.ServisKullaniciAdi = ServisKullaniciAdi;
            inValue.Body.ServisParola = ServisParola;
            inValue.Body.Konu = Konu;
            inValue.Body.PersonelSicil = PersonelSicil;
            inValue.Body.DokumanHash = DokumanHash;
            resumableUpload.ServiceReference1.SignResponse retVal = ((resumableUpload.ServiceReference1.signdocumentSoap)(this)).Sign(inValue);
            return retVal.Body.SignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<resumableUpload.ServiceReference1.SignResponse> resumableUpload.ServiceReference1.signdocumentSoap.SignAsync(resumableUpload.ServiceReference1.SignRequest request) {
            return base.Channel.SignAsync(request);
        }
        
        public System.Threading.Tasks.Task<resumableUpload.ServiceReference1.SignResponse> SignAsync(string ServisKullaniciAdi, string ServisParola, string Konu, string PersonelSicil, string DokumanHash) {
            resumableUpload.ServiceReference1.SignRequest inValue = new resumableUpload.ServiceReference1.SignRequest();
            inValue.Body = new resumableUpload.ServiceReference1.SignRequestBody();
            inValue.Body.ServisKullaniciAdi = ServisKullaniciAdi;
            inValue.Body.ServisParola = ServisParola;
            inValue.Body.Konu = Konu;
            inValue.Body.PersonelSicil = PersonelSicil;
            inValue.Body.DokumanHash = DokumanHash;
            return ((resumableUpload.ServiceReference1.signdocumentSoap)(this)).SignAsync(inValue);
        }
    }
}
