//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApi.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data3", Namespace="http://schemas.datacontract.org/2004/07/FHTWebTerminal.Servisler")]
    public enum data3 : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnCokAzalan = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncokArtan = 17,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data2", Namespace="http://schemas.datacontract.org/2004/07/FHTWebTerminal.Servisler")]
    public enum data2 : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayPiyasasi = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIOP = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Emtia = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data4", Namespace="http://schemas.datacontract.org/2004/07/FHTWebTerminal.Servisler")]
    public enum data4 : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnSonDegeri = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gunluk = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Haftalik = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aylik = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yillik = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data", Namespace="http://schemas.datacontract.org/2004/07/FHTWebTerminal.Servisler")]
    public enum data : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SonDakika = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Piyasa = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ekonomi = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisPolitika = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Siyaset = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Flaslar = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KAP = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sirket = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Raporlar = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Borsa = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Altin = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmtiaHaber = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnalizVeYorumlar = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SektorEndeksleri = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TCMBHaberleri = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TUIKHaberleri = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BDDKHaberleri = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HazineHaberleri = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SPKHaberleri = 24,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFinanceApi")]
    public interface IFinanceApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceArtanAzalanData", ReplyAction="http://tempuri.org/IFinanceApi/FinanceArtanAzalanDataResponse")]
        string FinanceArtanAzalanData(testApi.ServiceReference1.data3 data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceArtanAzalanData", ReplyAction="http://tempuri.org/IFinanceApi/FinanceArtanAzalanDataResponse")]
        System.Threading.Tasks.Task<string> FinanceArtanAzalanDataAsync(testApi.ServiceReference1.data3 data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceGetTCMBSayfalari", ReplyAction="http://tempuri.org/IFinanceApi/FinanceGetTCMBSayfalariResponse")]
        string FinanceGetTCMBSayfalari(string kod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceGetTCMBSayfalari", ReplyAction="http://tempuri.org/IFinanceApi/FinanceGetTCMBSayfalariResponse")]
        System.Threading.Tasks.Task<string> FinanceGetTCMBSayfalariAsync(string kod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceGetTCMBSayfalariList", ReplyAction="http://tempuri.org/IFinanceApi/FinanceGetTCMBSayfalariListResponse")]
        string FinanceGetTCMBSayfalariList(string[] kodList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceGetTCMBSayfalariList", ReplyAction="http://tempuri.org/IFinanceApi/FinanceGetTCMBSayfalariListResponse")]
        System.Threading.Tasks.Task<string> FinanceGetTCMBSayfalariListAsync(string[] kodList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceGetEmtia", ReplyAction="http://tempuri.org/IFinanceApi/FinanceGetEmtiaResponse")]
        string FinanceGetEmtia(testApi.ServiceReference1.data2 data, string emtia, testApi.ServiceReference1.data4 interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceGetEmtia", ReplyAction="http://tempuri.org/IFinanceApi/FinanceGetEmtiaResponse")]
        System.Threading.Tasks.Task<string> FinanceGetEmtiaAsync(testApi.ServiceReference1.data2 data, string emtia, testApi.ServiceReference1.data4 interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceEmtiaListData", ReplyAction="http://tempuri.org/IFinanceApi/FinanceEmtiaListDataResponse")]
        string FinanceEmtiaListData(testApi.ServiceReference1.data2 data, string[] emtiaListesi, testApi.ServiceReference1.data4 interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceEmtiaListData", ReplyAction="http://tempuri.org/IFinanceApi/FinanceEmtiaListDataResponse")]
        System.Threading.Tasks.Task<string> FinanceEmtiaListDataAsync(testApi.ServiceReference1.data2 data, string[] emtiaListesi, testApi.ServiceReference1.data4 interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceNewsData", ReplyAction="http://tempuri.org/IFinanceApi/FinanceNewsDataResponse")]
        string FinanceNewsData(testApi.ServiceReference1.data data, int NewsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceApi/FinanceNewsData", ReplyAction="http://tempuri.org/IFinanceApi/FinanceNewsDataResponse")]
        System.Threading.Tasks.Task<string> FinanceNewsDataAsync(testApi.ServiceReference1.data data, int NewsCount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinanceApiChannel : testApi.ServiceReference1.IFinanceApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanceApiClient : System.ServiceModel.ClientBase<testApi.ServiceReference1.IFinanceApi>, testApi.ServiceReference1.IFinanceApi {
        
        public FinanceApiClient() {
        }
        
        public FinanceApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanceApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FinanceArtanAzalanData(testApi.ServiceReference1.data3 data) {
            return base.Channel.FinanceArtanAzalanData(data);
        }
        
        public System.Threading.Tasks.Task<string> FinanceArtanAzalanDataAsync(testApi.ServiceReference1.data3 data) {
            return base.Channel.FinanceArtanAzalanDataAsync(data);
        }
        
        public string FinanceGetTCMBSayfalari(string kod) {
            return base.Channel.FinanceGetTCMBSayfalari(kod);
        }
        
        public System.Threading.Tasks.Task<string> FinanceGetTCMBSayfalariAsync(string kod) {
            return base.Channel.FinanceGetTCMBSayfalariAsync(kod);
        }
        
        public string FinanceGetTCMBSayfalariList(string[] kodList) {
            return base.Channel.FinanceGetTCMBSayfalariList(kodList);
        }
        
        public System.Threading.Tasks.Task<string> FinanceGetTCMBSayfalariListAsync(string[] kodList) {
            return base.Channel.FinanceGetTCMBSayfalariListAsync(kodList);
        }
        
        public string FinanceGetEmtia(testApi.ServiceReference1.data2 data, string emtia, testApi.ServiceReference1.data4 interval) {
            return base.Channel.FinanceGetEmtia(data, emtia, interval);
        }
        
        public System.Threading.Tasks.Task<string> FinanceGetEmtiaAsync(testApi.ServiceReference1.data2 data, string emtia, testApi.ServiceReference1.data4 interval) {
            return base.Channel.FinanceGetEmtiaAsync(data, emtia, interval);
        }
        
        public string FinanceEmtiaListData(testApi.ServiceReference1.data2 data, string[] emtiaListesi, testApi.ServiceReference1.data4 interval) {
            return base.Channel.FinanceEmtiaListData(data, emtiaListesi, interval);
        }
        
        public System.Threading.Tasks.Task<string> FinanceEmtiaListDataAsync(testApi.ServiceReference1.data2 data, string[] emtiaListesi, testApi.ServiceReference1.data4 interval) {
            return base.Channel.FinanceEmtiaListDataAsync(data, emtiaListesi, interval);
        }
        
        public string FinanceNewsData(testApi.ServiceReference1.data data, int NewsCount) {
            return base.Channel.FinanceNewsData(data, NewsCount);
        }
        
        public System.Threading.Tasks.Task<string> FinanceNewsDataAsync(testApi.ServiceReference1.data data, int NewsCount) {
            return base.Channel.FinanceNewsDataAsync(data, NewsCount);
        }
    }
}
